[package]
name = "tls-example"
version = "0.1.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]

[[bin]]
name = "server"
path = "src/main.rs"

[dependencies]
env_logger = "0.4"
actix = { version = "^0.3.5" }
actix-web = { git = "https://github.com/actix/actix-web", features=["signal", "alpn"] }
