[package]
name = "tls-example"
version = "0.1.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]

[[bin]]
name = "server"
path = "src/main.rs"

[dependencies]
env_logger = "0.4"

actix = "^0.3.1"
actix-web = { path = "../../", features=["alpn"] }
