language: rust
sudo: required
dist: trusty

cache:
  cargo: true
  apt: true

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly-2019-03-02
  allow_failures:
    - rust: nightly-2019-03-02

env:
  global:
    - RUSTFLAGS="-C link-dead-code"
    - OPENSSL_VERSION=openssl-1.0.2

before_install:
  - sudo add-apt-repository -y ppa:0k53d-karl-f830m/openssl
  - sudo apt-get update -qq
  - sudo apt-get install -y openssl libssl-dev libelf-dev libdw-dev cmake gcc binutils-dev libiberty-dev

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == "nightly-2019-03-02" ]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
  fi

# Add clippy
before_script:
  - export PATH=$PATH:~/.cargo/bin

script:
  - |
    if [[ "$TRAVIS_RUST_VERSION" != "nightly-2019-03-02" ]]; then
    cargo clean
    cargo test --features="ssl,tls,rust-tls" -- --nocapture
    cd actix-codec && cargo test && cd ..
    cd actix-service && cargo test && cd ..
    cd actix-server && cargo test --all-features -- --nocapture && cd ..
    cd actix-rt && cargo test && cd ..
    cd actix-connect && cargo test && cd ..
    cd actix-utils && cargo test && cd ..
    cd router && cargo test && cd ..
    fi

after_success:
  - |
    if [[ "$TRAVIS_RUST_VERSION" == "nightly-2019-03-02" ]]; then
    #cd actix-service && cargo tarpaulin --out Xml && bash <(curl -s https://codecov.io/bash) && cd ..
    #cd actix-rt && cargo tarpaulin --out Xml && bash <(curl -s https://codecov.io/bash) && cd ..
    #cd actix-connect && cargo tarpaulin --out Xml && bash <(curl -s https://codecov.io/bash) && cd ..
    #cd actix-codec && cargo tarpaulin --out Xml && bash <(curl -s https://codecov.io/bash) && cd ..
    #cd actix-server && cargo tarpaulin --out Xml && bash <(curl -s https://codecov.io/bash) && cd ..
    #cd actix-utils && cargo tarpaulin --out Xml && bash <(curl -s https://codecov.io/bash) && cd ..
    #cd router && cargo tarpaulin --out Xml && bash <(curl -s https://codecov.io/bash) && cd ..

    cd actix-service && taskset -c 0 cargo tarpaulin --out Xml && cd ..
    cd actix-rt && cargo taskset -c 0 tarpaulin --out Xml && cd ..
    cd actix-connect && taskset -c 0 cargo tarpaulin --out Xml && cd ..
    cd actix-codec && taskset -c 0 cargo tarpaulin --out Xml && cd ..
    cd actix-utils && taskset -c 0 cargo tarpaulin --out Xml && cd ..
    cd actix-server && taskset -c 0 cargo tarpaulin --all-features --out Xml && cd ..
    cd router && taskset -c 0 cargo tarpaulin --out Xml && cd ..

    # cargo tarpaulin --all --all-features --out Xml
    echo "Uploaded code coverage"
    bash <(curl -s https://codecov.io/bash)
    fi
