[workspace]
members = [
  "ntex",
  "ntex-codec",
  "ntex-macros",
  "ntex-router",
  "ntex-rt",
  "ntex-service",
  # "ntex-web-macros",

  "actix-net/actix-service",
  "actix-net/router",
]

[patch.crates-io]
ntex = { path = "ntex" }
ntex-codec = { path = "ntex-codec" }
ntex-macros = { path = "ntex-macros" }
ntex-router = { path = "ntex-router" }
ntex-rt = { path = "ntex-rt" }
ntex-service = { path = "ntex-service" }
ntex-web-macros = { path = "ntex-web-macros" }

bytestring = { path = "actix-net/string" }
