[workspace]
members = [
  "ntex",
  "ntex-router",
  "ntex-service",
  "ntex-web-macros",

  "actix-net/actix-service",
  "actix-net/router",
]

[patch.crates-io]
ntex = { path = "ntex" }
ntex-router = { path = "ntex-router" }
ntex-service = { path = "ntex-service" }

actix-service = { path = "actix-net/actix-service" }
actix-router = { path = "actix-net/router" }

actix-codec = { path = "actix-net/actix-codec" }
actix-connect = { path = "actix-net/actix-connect" }
actix-rt = { path = "actix-net/actix-rt" }
actix-macros = { path = "actix-net/actix-macros" }
bytestring = { path = "actix-net/string" }
