[package]
name = "awc"
version = "0.1.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
description = "Actix web client."
readme = "README.md"
keywords = ["http", "web", "framework", "async", "futures"]
homepage = "https://actix.rs"
repository = "https://github.com/actix/actix-web.git"
documentation = "https://docs.rs/awc/"
license = "MIT/Apache-2.0"
exclude = [".gitignore", ".travis.yml", ".cargo/config", "appveyor.yml"]
workspace = ".."
edition = "2018"

[lib]
name = "awc"
path = "src/lib.rs"

[features]
default = ["cookies"]

# openssl
ssl = ["openssl", "actix-http/ssl"]

# cookies integration
cookies = ["cookie", "actix-http/cookies"]

[dependencies]
actix-service = "0.3.4"
actix-http = { git = "https://github.com/actix/actix-http.git" }
bytes = "0.4"
futures = "0.1"
log =" 0.4"
percent-encoding = "1.0"
serde = "1.0"
serde_json = "1.0"
serde_urlencoded = "0.5.3"

cookie = { version="0.11", features=["percent-encode"], optional = true }
openssl = { version="0.10", optional = true }

[dev-dependencies]
env_logger = "0.6"
mime = "0.3"
actix-rt = "0.2.1"
actix-http = { git = "https://github.com/actix/actix-http.git", features=["ssl"] }
actix-http-test = { git = "https://github.com/actix/actix-http.git", features=["ssl"] }
