[package]
name = "hello-world"
version = "0.1.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
workspace = "../.."

[dependencies]
env_logger = "0.5"
actix = { git = "https://github.com/actix/actix.git" }
actix-web = { path = "../../" }
