[package]
name = "actix-cors"
version = "0.2.0-alpha.1"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
description = "Cross-origin resource sharing (CORS) for Actix applications."
readme = "README.md"
keywords = ["web", "framework"]
homepage = "https://actix.rs"
repository = "https://github.com/actix/actix-web.git"
documentation = "https://docs.rs/actix-cors/"
license = "MIT/Apache-2.0"
edition = "2018"
workspace = ".."

[lib]
name = "actix_cors"
path = "src/lib.rs"

[dependencies]
actix-web = "1.0.9"
actix-service = "0.4.0"
derive_more = "0.15.0"
futures = "0.3.1"
