[package]
name = "ntex-codec"
version = "0.4.0"
authors = ["ntex contributors <team@ntex.rs>"]
description = "Utilities for encoding and decoding frames"
keywords = ["network", "framework", "async", "futures"]
homepage = "https://ntex.rs"
repository = "https://github.com/ntex-rs/ntex.git"
documentation = "https://docs.rs/ntex-codec/"
categories = ["network-programming", "asynchronous"]
license = "MIT"
edition = "2018"

[lib]
name = "ntex_codec"
path = "src/lib.rs"

[dependencies]
bitflags = "1.2.1"
bytes = "1.0"
either = "1.6.1"
futures-core = "0.3.12"
futures-sink = "0.3.12"
log = "0.4"
tokio = { version = "1", default-features=false }

[dev-dependencies]
ntex = "0.3.0-b.1"
futures = "0.3.13"
