[package]
name = "ntex-codec"
version = "0.2.1"
authors = ["ntex contributors <team@ntex.rs>"]
description = "Utilities for encoding and decoding frames"
keywords = ["network", "framework", "async", "futures"]
homepage = "https://ntex.rs"
repository = "https://github.com/ntex-rs/ntex.git"
documentation = "https://docs.rs/ntex-codec/"
categories = ["network-programming", "asynchronous"]
license = "MIT"
edition = "2018"

[lib]
name = "ntex_codec"
path = "src/lib.rs"

[dependencies]
bitflags = "1.2.1"
bytes = "0.5.6"
either = "1.5.3"
futures-core = "0.3.5"
futures-sink = "0.3.5"
log = "0.4"
tokio = { version = "0.2.6", default-features=false }

[dev-dependencies]
ntex = "0.1.21"
futures = "0.3.5"
