[package]
name = "websocket"
version = "0.1.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]

[[bin]]
name = "server"
path = "src/main.rs"

[dependencies]
env_logger = "*"
futures = "0.1"
#actix = "0.4"
actix = { git = "https://github.com/actix/actix.git" }
actix-web = { git = "https://github.com/actix/actix-web.git" }
