[package]
name = "websocket"
version = "0.1.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]

[[bin]]
name = "server"
path = "src/main.rs"

[[bin]]
name = "client"
path = "src/client.rs"

[dependencies]
env_logger = "*"
futures = "0.1"
tokio-core = "0.1"
#actix = "^0.4.2"
actix = { git = "https://github.com/actix/actix.git" }
actix-web = { path="../../" }
