[package]
name = "ntex-router"
version = "0.4.1"
authors = ["ntex contributors <team@ntex.rs>"]
description = "Path router"
keywords = ["ntex"]
repository = "https://github.com/ntex-rs/ntex.git"
documentation = "https://docs.rs/ntex-router/"
license = "MIT"
edition = "2018"

[lib]
name = "ntex_router"
path = "src/lib.rs"

[features]
default = ["http"]

[dependencies]
regex = "1.4.1"
serde = "1.0.116"
bytestring = "1.0"
log = "0.4.8"
http = { version = "0.2.1", optional = true }

[dev-dependencies]
http = "0.2.1"
serde_derive = "1.0"
