[package]
name = "ntex-router"
version = "0.3.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
description = "Path router"
keywords = ["ntex"]
repository = "https://github.com/fafhrd91/ntex.git"
documentation = "https://docs.rs/ntex-router/"
license = "MIT"
edition = "2018"

[lib]
name = "ntex_router"
path = "src/lib.rs"

[features]
default = ["http"]

[dependencies]
regex = "1.3.5"
serde = "1.0.105"
bytestring = "0.1.2"
log = "0.4.8"
http = { version = "0.2.0", optional = true }

[dev-dependencies]
http = "0.2.0"
serde_derive = "1.0"
