[package]
name = "ntex-service"
version = "0.1.4"
authors = ["ntex contributors <team@ntex.rs>"]
description = "ntex service"
keywords = ["network", "framework", "async", "futures"]
homepage = "https://ntex.rs"
repository = "https://github.com/ntex-rs/ntex.git"
documentation = "https://docs.rs/ntex-service/"
categories = ["network-programming", "asynchronous"]
license = "MIT"
edition = "2018"

[lib]
name = "ntex_service"
path = "src/lib.rs"

[dependencies]
futures-util = "0.3.5"
pin-project = "0.4.20"
pin-project-lite = "0.1.5"

[dev-dependencies]
ntex-rt = "0.1"