[package]
name = "ntex-service"
version = "0.1.1"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
description = "ntex service"
keywords = ["network", "framework", "async", "futures"]
homepage = "https://ntex.rs"
repository = "https://github.com/ntex-rs/ntex.git"
documentation = "https://docs.rs/ntex-service/"
categories = ["network-programming", "asynchronous"]
license = "MIT"
edition = "2018"

[lib]
name = "ntex_service"
path = "src/lib.rs"

[dependencies]
futures-util = "0.3.4"
pin-project = "0.4.8"

[dev-dependencies]
ntex-rt = "0.1"