[package]
name = "ntex-rt"
version = "0.4.0-b.0"
authors = ["ntex contributors <team@ntex.rs>"]
description = "ntex runtime"
keywords = ["network", "framework", "async", "futures"]
homepage = "https://ntex.rs"
repository = "https://github.com/ntex-rs/ntex.git"
documentation = "https://docs.rs/ntex-rt/"
categories = ["network-programming", "asynchronous"]
license = "MIT"
edition = "2018"

[lib]
name = "ntex_rt"
path = "src/lib.rs"

[features]
default = ["tokio"]

# tokio support
tokio = ["tok-io", "ntex-io/tokio"]

[dependencies]
ntex-bytes = "0.1.7"
ntex-io = "0.1.0"
ntex-util = "0.1.2"
async-oneshot = "0.5.0"
async-channel = "1.6.1"
log = "0.4"
pin-project-lite = "0.2"

tok-io = { version = "1", package = "tokio", default-features = false, features = ["rt", "net", "signal"], optional = true }
