[package]
name = "actix-codec"
version = "0.2.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
description = "Actix codec"
keywords = ["network", "framework", "async", "futures"]
homepage = "https://actix.rs"
repository = "https://github.com/actix/actix-net.git"
documentation = "https://docs.rs/actix-service/"
categories = ["network-programming", "asynchronous"]
license = "MIT/Apache-2.0"
edition = "2018"

[badges]
travis-ci = { repository = "actix/actix-service", branch = "master" }
codecov = { repository = "actix/actix-service", branch = "master", service = "github" }

[lib]
name = "actix_codec"
path = "src/lib.rs"

[dependencies]
ntex-codec = "0.3.0"
