[package]
name = "template-tera"
version = "0.1.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]

[dependencies]
env_logger = "0.4"
actix = "^0.3.1"
actix-web = { git = "https://github.com/actix/actix-web.git" }
tera = "*"
