[package]
name = "basics"
version = "0.1.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
workspace = "../.."

[dependencies]
futures = "*"
env_logger = "0.4"
actix = "0.4"
actix-web = { path = "../../" }
