[package]
name = "ntex"
version = "0.1.24"
authors = ["ntex contributors <team@ntex.rs>"]
description = "Framework for composable network services"
readme = "README.md"
keywords = ["ntex", "networking", "framework", "async", "futures"]
repository = "https://github.com/ntex-rs/ntex.git"
documentation = "https://docs.rs/ntex/"
categories = ["network-programming", "asynchronous",
              "web-programming::http-server",
              "web-programming::websocket"]
license = "MIT"
edition = "2018"

[package.metadata.docs.rs]
features = ["openssl", "rustls", "compress", "cookie"]

[lib]
name = "ntex"
path = "src/lib.rs"

[features]
default = []

# openssl
openssl = ["open-ssl", "tokio-openssl"]

# rustls support
rustls = ["rust-tls", "webpki", "webpki-roots", "tokio-rustls"]

# enable compressison support
compress = ["flate2", "brotli2"]

# enable cookie support
cookie = ["coo-kie", "coo-kie/percent-encode"]

[dependencies]
ntex-codec = "0.1.2"
ntex-rt = "0.1.1"
ntex-rt-macros = "0.1"
ntex-router = "0.3.7"
ntex-service = "0.1.3"
ntex-macros = "0.1"

actix-threadpool = "0.3.3"
base64 = "0.12"
bitflags = "1.2.1"
bytes = "0.5.6"
bytestring = "0.1.5"
derive_more = "0.99.5"
either = "1.5.3"
encoding_rs = "0.8.22"
futures = "0.3.5"
fxhash = "0.2.1"
h2 = "0.2.4"
http = "0.2.1"
httparse = "1.3"
lazy_static = "1.4"
log = "0.4"
mime = "0.3"
mio = "0.6.22"
num_cpus = "1.12"
percent-encoding = "2.1"
pin-project = "0.4.20"
pin-project-lite = "0.1.7"
rand = "0.7"
regex = "1.3"
sha-1 = "0.9.1"
slab = "0.4.2"
serde = { version = "1.0", features=["derive"] }
serde_json = "1.0"
serde_urlencoded = "0.7.0"
socket2 = "0.3.12"
url = "2.1"
time = { version = "0.2.11", default-features = false, features = ["std"] }
coo-kie = { version = "0.14.2", package = "cookie", optional = true }
tokio = "0.2.6"

# resolver
trust-dns-proto = { version = "0.19.3", default-features = false }
trust-dns-resolver = { version = "0.19.3", default-features = false, features=["system-config"] }
async-trait = "0.1.27" # this is only for trust-dns

# FIXME: Remove it and use mio own uds feature once mio 0.7 is released
mio-uds = { version = "0.6.7" }

# openssl
open-ssl = { version="0.10", package = "openssl", optional = true }
tokio-openssl = { version = "0.4.0", optional = true }

# rustls
rust-tls = { version = "0.18.0", package = "rustls", optional = true }
webpki = { version = "0.21.2", optional = true }
webpki-roots = { version = "0.20.0", optional = true }
tokio-rustls = { version = "0.14.0", optional = true }

# compression
brotli2 = { version="0.3.2", optional = true }
flate2 = { version = "1.0.14", optional = true }

[dev-dependencies]
futures = "0.3.4"
env_logger = "0.7"
serde_derive = "1.0"
open-ssl = { version="0.10", package = "openssl" }
rust-tls = { version = "0.18.0", package="rustls", features = ["dangerous_configuration"]  }
webpki = "0.21.2"
