[package]
name = "ntex"
version = "0.1.1"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
description = "Framework for composable network services"
readme = "README.md"
keywords = ["ntex", "networking", "framework", "async", "futures"]
repository = "https://github.com/fafhrd91/ntex.git"
documentation = "https://docs.rs/ntex/"
categories = ["network-programming", "asynchronous",
              "web-programming::http-server",
              "web-programming::websocket"]
license = "MIT"
edition = "2018"

[package.metadata.docs.rs]
features = ["openssl", "rustls", "compress", "cookie"]

[lib]
name = "ntex"
path = "src/lib.rs"

[features]
default = []

# openssl
openssl = ["open-ssl", "tokio-openssl"]

# rustls support
rustls = ["rust-tls", "webpki", "webpki-roots", "tokio-rustls"]

# enable compressison support
compress = ["flate2", "brotli2"]

# enable cookie support
cookie = ["coo-kie", "coo-kie/percent-encode"]

[dependencies]
ntex-codec = "0.1"
ntex-rt = "0.1"
ntex-rt-macros = "0.1"
ntex-router = "0.3"
ntex-service = "0.1"
ntex-web-macros = "0.1"

actix-threadpool = "0.3.1"
base64 = "0.11"
bitflags = "1.2"
bytes = "0.5.3"
bytestring = "0.1.5"
derive_more = "0.99.2"
either = "1.5.3"
encoding_rs = "0.8"
futures = "0.3.1"
fxhash = "0.2.1"
h2 = "0.2.1"
http = "0.2.0"
httparse = "1.3"
indexmap = "1.3"
lazy_static = "1.4"
log = "0.4"
mime = "0.3"
mio = "0.6.19"
net2 = "0.2.33"
num_cpus = "1.11"
percent-encoding = "2.1"
pin-project = "0.4.6"
rand = "0.7"
regex = "1.3"
sha-1 = "0.8"
slab = "0.4"
serde = { version = "1.0", features=["derive"] }
serde_json = "1.0"
serde_urlencoded = "0.6.1"
url = "2.1"
time = { version = "0.2.5", default-features = false, features = ["std"] }
coo-kie = { version = "0.13.3", package = "cookie", optional = true }
trust-dns-proto = "=0.18.0-alpha.2"
trust-dns-resolver = "=0.18.0-alpha.2"

# openssl
open-ssl = { version="0.10", package = "openssl", optional = true }
tokio-openssl = { version = "0.4.0", optional = true }

# rustls
rust-tls = { version = "0.16.0", package = "rustls", optional = true }
webpki = { version = "0.21", optional = true }
webpki-roots = { version = "0.17", optional = true }
tokio-rustls = { version = "0.12.0", optional = true }

# FIXME: Remove it and use mio own uds feature once mio 0.7 is released
mio-uds = { version = "0.6.7" }

# compression
brotli2 = { version="0.3.2", optional = true }
flate2 = { version = "1.0.13", optional = true }

tokio = "0.2.6"

[dev-dependencies]
futures = "0.3.1"
env_logger = "0.7"
serde_derive = "1.0"
open-ssl = { version="0.10", package = "openssl" }
rust-tls = { version = "0.16.0", package="rustls", features = ["dangerous_configuration"]  }
webpki = "0.21"
