[package]
name = "Actix-web-CORS"
version = "0.1.0"
authors = ["krircc <krircc@aliyun.com>"]

[dependencies]
serde = "^1.0.0"
serde_derive = "^1.0.0"
serde_json = "^1.0.0"
http = "^0.1.0"
num_cpus = "1.0"

actix = "^0.4.0"
actix-web = { git = "https://github.com/actix/actix-web" }
dotenv = "^0.10.0"
env_logger = "^0.5.0"
futures = "0.1"